import { StyleSheet } from 'react-native';

export const colors = {
  background: '#000000',
  surface: '#101214',
  surfaceRaised: '#20252a',
  border: '#2d3339',
  text: '#f4f6f8',
  textMuted: '#9da5ad',
  accent: '#8ee6b1',
  accentPressed: '#6dcc93',
  danger: '#ff8d8d',
};

export const spacing = {
  xs: 8,
  sm: 12,
  md: 18,
  lg: 26,
  xl: 38,
};

export const styles = StyleSheet.create({
  safeArea: { flex: 1, backgroundColor: colors.background },
  screen: { flex: 1, backgroundColor: colors.background },
  content: { width: '100%', maxWidth: 760, alignSelf: 'center', padding: spacing.lg },
  loginContent: { flexGrow: 1, justifyContent: 'center' },
  eyebrow: { color: colors.accent, fontSize: 13, fontWeight: '700', letterSpacing: 1.4, textTransform: 'uppercase' },
  title: { color: colors.text, fontSize: 34, fontWeight: '800', marginTop: spacing.sm },
  subtitle: { color: colors.textMuted, fontSize: 16, lineHeight: 24, marginTop: spacing.sm },
  form: { marginTop: spacing.xl },
  label: { color: colors.textMuted, fontSize: 13, fontWeight: '700', marginBottom: spacing.xs, textTransform: 'uppercase' },
  input: { backgroundColor: colors.surface, borderColor: colors.border, borderRadius: 8, borderWidth: 1, color: colors.text, fontSize: 16, marginBottom: spacing.md, padding: 15 },
  datePickerButton: { alignItems: 'center', backgroundColor: colors.surface, borderColor: colors.border, borderRadius: 8, borderWidth: 1, flexDirection: 'row', justifyContent: 'space-between', marginBottom: spacing.md, padding: 15 },
  datePickerValue: { color: colors.text, fontSize: 16 },
  datePickerPlaceholder: { color: colors.textMuted, fontSize: 16 },
  datePickerNativeInput: { color: colors.text, flex: 1, fontSize: 16, padding: 0 },
  datePickerWebWrapper: { marginBottom: spacing.md },
  button: { alignItems: 'center', backgroundColor: colors.accent, borderRadius: 8, padding: 16 },
  buttonContent: { alignItems: 'center', flexDirection: 'row', gap: spacing.sm, justifyContent: 'center' },
  buttonPressed: { backgroundColor: colors.accentPressed },
  buttonText: { color: colors.background, fontSize: 16, fontWeight: '800' },
  error: { color: colors.danger, fontSize: 14, marginBottom: spacing.md },
  dashboardTopBar: { alignItems: 'center', borderBottomColor: colors.border, borderBottomWidth: 1, flexDirection: 'row', paddingHorizontal: spacing.lg, paddingVertical: spacing.sm },
  appName: { color: colors.text, fontSize: 20, fontWeight: '800' },
  header: { alignItems: 'center', flexDirection: 'row', marginBottom: spacing.xl },
  headerCopy: { flex: 1, paddingRight: spacing.md },
  dashboardActions: { flexDirection: 'row', gap: spacing.sm },
  dashboardActionsSection: { marginBottom: spacing.xl },
  dashboardAction: { alignItems: 'center', backgroundColor: colors.surfaceRaised, borderColor: colors.border, borderRadius: 8, borderWidth: 1, flex: 1, height: 88, justifyContent: 'center', minWidth: 0, padding: spacing.sm },
  dashboardActionIcon: { color: colors.accent },
  dashboardActionText: { color: colors.text, fontSize: 13, fontWeight: '700', marginTop: spacing.xs, textAlign: 'center' },
  clientFilters: { marginBottom: spacing.xl },
  clientFilterInput: { backgroundColor: colors.surface, borderColor: colors.border, borderRadius: 8, borderWidth: 1, color: colors.text, fontSize: 16, marginBottom: spacing.sm, padding: 15 },
  clientFilterToggle: { borderColor: colors.border, borderRadius: 8, borderWidth: 1, flexDirection: 'row', overflow: 'hidden' },
  clientFilterButton: { alignItems: 'center', flex: 1, justifyContent: 'center', minHeight: 42, paddingHorizontal: spacing.xs },
  clientFilterButtonActive: { backgroundColor: colors.accent },
  clientFilterButtonText: { color: colors.textMuted, fontSize: 12, fontWeight: '700', textAlign: 'center' },
  clientFilterButtonTextActive: { color: colors.background },
  viewMoreButton: { alignItems: 'center', borderColor: colors.border, borderRadius: 8, borderWidth: 1, marginTop: 0, padding: spacing.sm },
  dashboardOrdersSection: { marginBottom: spacing.xl },
  viewMoreText: { color: colors.accent, fontSize: 14, fontWeight: '700' },
  menuButton: { marginRight: spacing.md, padding: spacing.xs },
  menuIcon: { color: colors.text },
  section: { marginBottom: spacing.lg },
  sectionHeader: { alignItems: 'center', flexDirection: 'row', justifyContent: 'space-between', paddingBottom: spacing.sm },
  sectionToggle: { alignItems: 'center', flex: 1, flexDirection: 'row', gap: spacing.sm, minHeight: 36 },
  sectionTitle: { color: colors.text, fontSize: 20, fontWeight: '800', marginBottom: spacing.sm },
  sectionTitleNoMargin: { marginBottom: 0 },
    addButton: { alignItems: 'center', backgroundColor: colors.accent, borderRadius: 18, height: 36, justifyContent: 'center', width: 36 },
    addButtonText: { color: colors.background },
  listItem: { marginBottom: spacing.sm, paddingVertical: spacing.sm },
  listItemPressed: { opacity: 0.65 },
  card: { backgroundColor: colors.surface, borderRadius: 8, marginBottom: spacing.sm, padding: spacing.md },
  cardRow: { alignItems: 'center', flexDirection: 'row', justifyContent: 'space-between' },
  cardTitleBlock: { flex: 1 },
  cardTitle: { color: colors.text, flex: 1, fontSize: 16, fontWeight: '700' },
  cardMeta: { color: colors.textMuted, fontSize: 14, marginTop: 5 },
  cardValue: { color: colors.accent, fontSize: 16, fontWeight: '800', marginLeft: spacing.sm },
  pendingOrderCard: { borderLeftColor: colors.accent, borderLeftWidth: 4 },
  resolvedOrderCard: { borderLeftColor: colors.textMuted, borderLeftWidth: 4, opacity: 0.72 },
  pendingOrderText: { color: colors.accent },
  resolvedOrderText: { color: colors.textMuted },
  orderObservations: { color: colors.textMuted, fontSize: 14, lineHeight: 20, marginTop: spacing.sm },
  orderStatusButton: { alignItems: 'center', borderColor: colors.border, borderRadius: 8, borderWidth: 1, flexDirection: 'row', gap: spacing.sm, justifyContent: 'center', marginTop: spacing.md, padding: 10 },
  orderStatusText: { color: colors.textMuted, fontSize: 13, fontWeight: '700' },
  empty: { color: colors.textMuted, fontSize: 14, paddingVertical: spacing.sm },
  loading: { marginTop: spacing.xl },
  backButton: { alignSelf: 'flex-start', marginBottom: spacing.xl },
  backText: { color: colors.accent, fontSize: 14, fontWeight: '700' },
  detailHeader: { marginBottom: spacing.xl },
  nameRow: { alignItems: 'center', flexDirection: 'row' },
  editIconButton: { alignItems: 'center', alignSelf: 'center', justifyContent: 'center', marginLeft: spacing.sm, marginTop: spacing.sm, padding: spacing.sm },
  detailValue: { color: colors.text, fontSize: 17, marginBottom: 0 },
  detailRow: { alignItems: 'center', flexDirection: 'row', marginBottom: spacing.lg, minHeight: 44 },
  detailRowInfo: { flex: 1, marginRight: spacing.sm },
  detailRowInfoFull: { flex: 1 },
  detailInput: { marginBottom: 0 },
  detailTextarea: { minHeight: 96, textAlignVertical: 'top' },
  detailActionSlot: { height: 44, width: 44 },
  secondaryButton: { alignItems: 'center', borderColor: colors.border, borderRadius: 8, borderWidth: 1, marginTop: spacing.md, padding: 16 },
  secondaryText: { color: colors.textMuted, fontSize: 16, fontWeight: '800' },
  deleteButton: { alignItems: 'center', borderColor: colors.danger, borderRadius: 8, borderWidth: 1, marginTop: spacing.md, padding: 16 },
  deleteText: { color: colors.danger, fontSize: 16, fontWeight: '800' },
  whatsappButton: { alignItems: 'center', backgroundColor: '#25D366', borderRadius: 22, height: 44, justifyContent: 'center', width: 44 },
  whatsappText: { color: '#071b0d', fontSize: 16, fontWeight: '800' },
  mapsButton: { alignItems: 'center', backgroundColor: colors.accent, borderRadius: 22, height: 44, justifyContent: 'center', width: 44 },
  mapsText: { color: colors.background, fontSize: 16, fontWeight: '800' },
  facebookButton: { alignItems: 'center', backgroundColor: '#1877F2', borderRadius: 22, height: 44, justifyContent: 'center', width: 44 },
  facebookText: { color: '#ffffff', fontSize: 16, fontWeight: '800' },
  buttonDisabled: { backgroundColor: colors.border },
  detailSection: { marginTop: spacing.xl },
  sectionHeading: { alignItems: 'center', flexDirection: 'row', gap: spacing.sm },
  statisticsSummary: { flexDirection: 'row', gap: spacing.sm, marginBottom: spacing.xl },
  statisticsMetric: { alignItems: 'center', backgroundColor: colors.surfaceRaised, borderColor: colors.border, borderRadius: 8, borderWidth: 1, flex: 1, height: 126, justifyContent: 'flex-start', minWidth: 0, padding: spacing.md },
  statisticsMetricIcon: { color: colors.accent, height: 20, width: 20 },
  statisticsMetricValue: { color: colors.text, fontSize: 26, fontWeight: '800', height: 34, lineHeight: 31, marginTop: spacing.xs, textAlign: 'center' },
  statisticsMetricLabel: { color: colors.text, fontSize: 13, marginTop: spacing.xs },
  statisticsMetricDetail: { color: colors.text, fontSize: 12, marginTop: spacing.xs },
  statisticsBlock: { marginBottom: spacing.xl },
  statisticsRow: { alignItems: 'center', borderBottomColor: colors.border, borderBottomWidth: 1, flexDirection: 'row', justifyContent: 'space-between', paddingVertical: spacing.sm },
  statisticsRowLabel: { color: colors.text, flex: 1, fontSize: 15, paddingRight: spacing.sm },
  statisticsRowValue: { color: colors.accent, fontSize: 14, fontWeight: '700' },
  statisticsChartRow: { alignItems: 'center', flexDirection: 'row', gap: spacing.sm, marginBottom: spacing.sm },
  statisticsChartLabel: { color: colors.textMuted, flexShrink: 0, fontSize: 13, textAlign: 'right', width: 64 },
  statisticsBarTrack: { backgroundColor: colors.surface, borderRadius: 4, flex: 1, height: 24, justifyContent: 'center', overflow: 'hidden', position: 'relative' },
  statisticsBar: { backgroundColor: colors.accent, borderRadius: 4, height: '100%' },
  statisticsChartValue: { color: '#ffffff', fontSize: 13, fontWeight: '800', left: 0, position: 'absolute', right: 0, textAlign: 'center', textShadowColor: '#000000', textShadowRadius: 3, top: 4 },
  statisticsPeriodHeader: { alignItems: 'center', flexDirection: 'row', justifyContent: 'space-between', marginBottom: spacing.md },
  statisticsPeriodToggle: { borderColor: colors.border, borderRadius: 8, borderWidth: 1, flexDirection: 'row', overflow: 'hidden' },
  statisticsPeriodButton: { paddingHorizontal: spacing.sm, paddingVertical: spacing.xs },
  statisticsPeriodButtonActive: { backgroundColor: colors.accent },
  statisticsPeriodButtonText: { color: colors.textMuted, fontSize: 13, fontWeight: '700' },
  statisticsPeriodButtonTextActive: { color: colors.background },
  statisticsCaption: { color: colors.textMuted, fontSize: 13, marginTop: -spacing.sm },
  noteComposer: { alignItems: 'center', flexDirection: 'row', gap: spacing.sm, marginBottom: spacing.md, marginTop: spacing.sm },
  noteInput: { backgroundColor: colors.surface, borderColor: colors.border, borderRadius: 8, borderWidth: 1, color: colors.text, flex: 1, minHeight: 80, padding: 15, textAlignVertical: 'top' },
  noteAddButton: { alignItems: 'center', backgroundColor: colors.accent, borderRadius: 22, height: 44, justifyContent: 'center', width: 44 },
  noteAddText: { color: colors.background, fontSize: 15, fontWeight: '800' },
  noteItem: { alignItems: 'flex-start', backgroundColor: colors.surface, borderColor: colors.border, borderRadius: 8, borderWidth: 1, flexDirection: 'row', marginBottom: spacing.sm, padding: spacing.md },
  noteCopy: { flex: 1, paddingRight: spacing.sm },
  noteText: { color: colors.text, fontSize: 15, lineHeight: 22 },
  drawerOverlay: { backgroundColor: 'rgba(0, 0, 0, 0.5)', flex: 1, flexDirection: 'row' },
  drawer: { backgroundColor: colors.surface, borderRightColor: colors.border, borderRightWidth: 1, padding: spacing.lg, width: 290 },
  drawerBackdrop: { flex: 1 },
  drawerHeader: { alignItems: 'flex-start', flexDirection: 'row', justifyContent: 'space-between' },
  drawerTitle: { color: colors.text, fontSize: 28, fontWeight: '800', marginTop: spacing.xs },
  iconButton: { padding: spacing.xs },
  drawerMenu: { marginTop: spacing.xl },
  navItem: { alignItems: 'center', borderRadius: 8, flexDirection: 'row', gap: spacing.md, marginBottom: spacing.xs, padding: spacing.md },
  navItemText: { color: colors.text, fontSize: 15, fontWeight: '700' },
  drawerFooter: { borderTopColor: colors.border, borderTopWidth: 1, marginTop: 'auto', paddingTop: spacing.md },
  drawerLogoutButton: { alignItems: 'center', flexDirection: 'row', gap: spacing.md, padding: spacing.md },
  drawerLogoutText: { color: colors.danger, fontSize: 15, fontWeight: '700' },
});
